import { Address, OrderItem, OrderStatus } from './index';

export type SupplierType = 'cjdropshipping' | 'deodap' | 'custom';
export type SupplierStatus = 'active' | 'inactive' | 'testing';

export interface SupplierCredentials {
  apiKey?: string;
  apiSecret?: string;
  accessToken?: string;
  email?: string;
  partnerId?: string;
  webhookSecret?: string;
  baseUrl?: string;
}

export interface SupplierPricingRule {
  markupType: 'percentage' | 'fixed' | 'multiplier';
  markupValue: number; // e.g. 50 for +50%, or 500 for +500 INR, or 2.5 for 2.5x
  minimumMarginPercent: number; // e.g. 30%
  roundToEnding: number; // e.g. 99, 499, 999
  currency: string; // 'INR', 'USD', etc.
  exchangeRateToINR: number; // e.g. 87.5 for USD to INR
}

export interface SupplierSettings {
  autoFulfillEnabled: boolean; // Auto-push paid orders to supplier API immediately
  autoSyncInventory: boolean; // Periodically sync stock levels
  autoSyncTracking: boolean; // Poll for tracking / AWB updates
  defaultShippingMethod: string; // e.g. 'CJPacket Ordinary', 'Delhivery Express', 'BlueDart'
  notifyCustomerOnTrackingSync: boolean;
  pricingRule: SupplierPricingRule;
}

export interface SupplierStats {
  totalProductsMapped: number;
  totalOrdersFulfilled: number;
  totalSpend: number;
  lastSyncAt?: string;
  lastError?: string;
}

export interface Supplier {
  id: string;
  name: string;
  type: SupplierType;
  description: string;
  websiteUrl: string;
  status: SupplierStatus;
  credentials: SupplierCredentials;
  settings: SupplierSettings;
  stats: SupplierStats;
  createdAt: string;
  updatedAt: string;
}

export interface SupplierVariantMapping {
  ozeiraVariantId: string;
  supplierVariantId: string;
  supplierSku: string;
  variantName: string;
  costPrice: number;
  stockQuantity: number;
}

export interface SupplierProductMapping {
  id: string;
  productId: string; // Ozeira product ID
  productTitle: string;
  productSku: string;
  supplierId: string;
  supplierName: string;
  supplierProductId: string;
  supplierSku: string;
  supplierPrice: number; // Base cost price in supplier currency
  supplierPriceINR: number; // Base cost price converted to INR
  retailPrice: number; // Selling price on Ozeira
  marginPercent: number; // Calculated profit margin %
  supplierStock: number;
  supplierUrl?: string;
  supplierImageUrl?: string;
  variantMappings: SupplierVariantMapping[];
  autoSyncStock: boolean;
  lastSyncedAt: string;
  createdAt: string;
}

export type SupplierOrderStatus =
  | 'unfulfilled'
  | 'queued'
  | 'pushed'
  | 'processing'
  | 'shipped'
  | 'delivered'
  | 'failed'
  | 'cancelled';

export interface SupplierFulfillmentItem {
  productId: string;
  variantId?: string;
  ozeiraSku: string;
  supplierSku: string;
  productTitle: string;
  quantity: number;
  unitCostINR: number;
  totalCostINR: number;
  productImage: string;
}

export interface SupplierFulfillmentOrder {
  id: string;
  orderId: string; // Ozeira internal Order ID
  orderNumber: string; // e.g. OZ-2026-3017
  supplierId: string;
  supplierName: string;
  supplierType: SupplierType;
  supplierOrderId?: string; // Order ref generated by CJ/DeoDap
  supplierStatus: SupplierOrderStatus;
  items: SupplierFulfillmentItem[];
  totalCostINR: number;
  shippingAddress: Address;
  shippingMethod: string;
  trackingNumber?: string;
  trackingCourier?: string;
  trackingUrl?: string;
  errorMessage?: string;
  retryCount: number;
  pushedAt?: string;
  shippedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SupplierCatalogItem {
  id: string;
  supplierId: string;
  supplierName: string;
  supplierType: SupplierType;
  supplierSku: string;
  title: string;
  description: string;
  category: string;
  costPrice: number;
  costCurrency: string;
  costPriceINR: number;
  suggestedRetailPriceINR: number;
  estimatedMarginPercent: number;
  stockQuantity: number;
  imageUrl: string;
  additionalImages: string[];
  variants: Array<{
    id: string;
    sku: string;
    name: string;
    size?: string;
    color?: string;
    costPriceINR: number;
    stock: number;
    imageUrl?: string;
  }>;
  specifications: Record<string, string>;
  originCountry: string;
  shippingTimeDays: string;
  isAlreadyImported?: boolean;
}

export interface SupplierApiLog {
  id: string;
  supplierId: string;
  supplierName: string;
  action: 'test_connection' | 'search_products' | 'create_order' | 'sync_tracking' | 'sync_inventory';
  status: 'success' | 'error';
  requestPayload?: any;
  responsePayload?: any;
  durationMs: number;
  timestamp: string;
}
